version: "3.2"

services:
  influxdb:
    image: "influxdb"
    volumes:
      - ./:/var/lib/influxdb
    ports:
      - 8086:8086

  graphana:
    image: "grafana/grafana"
    volumes:
      - ./graphana:/var/lib/grafana
    ports:
      - 3000:3000
